### ISSUE TITLE
Problem compiling OS X Yosemite + CUDA 7.0 + stdlibc++  

### ISSUE THREAD

**Issue by pedropgusmao** [vlfeat/matconvnet#152]
Good morning,

I ran into a problem while trying to compile matconvnet in an OS X Yosemite 10.10.3 (14D136) using Matlab 2014a with CUDA 7.0 . Below I report the error, the command I originally issued and the result of `make info` for the compiling flags.

I suspect the problem to be the use of '-stdlib=libstdc++' in the `MEXFLAGS_NVCC` flag instead of libc++ since I get:    
```
Undefined symbols for architecture x86_64:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(char const*, unsigned long)" 
```

The command I originally issued was: 
```
make ARCH=maci64 MATLABROOT=/Applications/MATLAB_R2014a.app \ 
ENABLE_GPU=yes \ 
CUDAROOT=/Developer/NVIDIA/CUDA-7.0 \ 
CUDAMETHOD=nvcc
```
 
and the error starts at 
```
...
Building with 'Xcode Clang++'.
MEX completed successfully.
mv -f "imread_quartz.o" "matlab/mex/.build/impl/imread_quartz.o"
/Developer/NVIDIA/CUDA-7.0/bin/nvcc -gencode=arch=compute_30,code=\"sm_30,compute_30\" -DENABLE_GPU  -I"/Applications/MATLAB_R2014a.app/extern/include" -I"/Applications/MATLAB_R2014a.app/toolbox/distcomp/gpu/extern/include" -Xcompiler -fPIC -DNDEBUG -O3 -g \
	"matlab/src/bits/impl/im2row_gpu.cu" -c -o "matlab/mex/.build/impl/im2row_gpu.o" 2> >( sed 's/^\(.*\)(\([0-9][0-9]*\)): \([ew].*\)/\1:\2: \3/g' >&2 )
/Developer/NVIDIA/CUDA-7.0/bin/nvcc -gencode=arch=compute_30,code=\"sm_30,compute_30\" -DENABLE_GPU  -I"/Applications/MATLAB_R2014a.app/extern/include" -I"/Applications/MATLAB_R2014a.app/toolbox/distcomp/gpu/extern/include" -Xcompiler -fPIC -DNDEBUG -O3 -g \
	"matlab/src/bits/impl/subsample_gpu.cu" -c -o "matlab/mex/.build/impl/subsample_gpu.o" 2> >( sed 's/^\(.*\)(\([0-9][0-9]*\)): \([ew].*\)/\1:\2: \3/g' >&2 )
/Developer/NVIDIA/CUDA-7.0/bin/nvcc -gencode=arch=compute_30,code=\"sm_30,compute_30\" -DENABLE_GPU  -I"/Applications/MATLAB_R2014a.app/extern/include" -I"/Applications/MATLAB_R2014a.app/toolbox/distcomp/gpu/extern/include" -Xcompiler -fPIC -DNDEBUG -O3 -g \
	"matlab/src/bits/impl/copy_gpu.cu" -c -o "matlab/mex/.build/impl/copy_gpu.o" 2> >( sed 's/^\(.*\)(\([0-9][0-9]*\)): \([ew].*\)/\1:\2: \3/g' >&2 )
/Developer/NVIDIA/CUDA-7.0/bin/nvcc -gencode=arch=compute_30,code=\"sm_30,compute_30\" -DENABLE_GPU  -I"/Applications/MATLAB_R2014a.app/extern/include" -I"/Applications/MATLAB_R2014a.app/toolbox/distcomp/gpu/extern/include" -Xcompiler -fPIC -DNDEBUG -O3 -g \
	"matlab/src/bits/impl/pooling_gpu.cu" -c -o "matlab/mex/.build/impl/pooling_gpu.o" 2> >( sed 's/^\(.*\)(\([0-9][0-9]*\)): \([ew].*\)/\1:\2: \3/g' >&2 )
/Developer/NVIDIA/CUDA-7.0/bin/nvcc -gencode=arch=compute_30,code=\"sm_30,compute_30\" -DENABLE_GPU  -I"/Applications/MATLAB_R2014a.app/extern/include" -I"/Applications/MATLAB_R2014a.app/toolbox/distcomp/gpu/extern/include" -Xcompiler -fPIC -DNDEBUG -O3 -g \
	"matlab/src/bits/impl/normalize_gpu.cu" -c -o "matlab/mex/.build/impl/normalize_gpu.o" 2> >( sed 's/^\(.*\)(\([0-9][0-9]*\)): \([ew].*\)/\1:\2: \3/g' >&2 )
/Developer/NVIDIA/CUDA-7.0/bin/nvcc -gencode=arch=compute_30,code=\"sm_30,compute_30\" -DENABLE_GPU  -I"/Applications/MATLAB_R2014a.app/extern/include" -I"/Applications/MATLAB_R2014a.app/toolbox/distcomp/gpu/extern/include" -Xcompiler -fPIC -DNDEBUG -O3 -g \
	"matlab/src/bits/datacu.cu" -c -o "matlab/mex/.build/datacu.o" 2> >( sed 's/^\(.*\)(\([0-9][0-9]*\)): \([ew].*\)/\1:\2: \3/g' >&2 )
/Developer/NVIDIA/CUDA-7.0/bin/nvcc -gencode=arch=compute_30,code=\"sm_30,compute_30\" -DENABLE_GPU  -I"/Applications/MATLAB_R2014a.app/extern/include" -I"/Applications/MATLAB_R2014a.app/toolbox/distcomp/gpu/extern/include" -Xcompiler -fPIC -DNDEBUG -O3 -g -Xcompiler -fPIC \
	"matlab/src/vl_nnconv.cu" -c -o "matlab/mex/.build/vl_nnconv.o" 2> >( sed 's/^\(.*\)(\([0-9][0-9]*\)): \([ew].*\)/\1:\2: \3/g' >&2 )
/Applications/MATLAB_R2014a.app/bin/mex -cxx -largeArrayDims -lmwblas -DENABLE_GPU  -DNDEBUG -O CXXOPTIMFLAGS='$CXXOPTIMFLAGS -g' LDOPTIMFLAGS='$LDOPTIMFLAGS -g'  LDFLAGS='$LDFLAGS -framework Cocoa -framework ImageIO' -lmwgpu -L/Developer/NVIDIA/CUDA-7.0/lib LDFLAGS='$LDFLAGS -stdlib=libstdc++' -lcublas -lcudart  "matlab/mex/.build/vl_nnconv.o" -output "matlab/mex/vl_nnconv.mexmaci64" matlab/mex/.build/data.o matlab/mex/.build/datamex.o matlab/mex/.build/nnconv.o matlab/mex/.build/nnbias.o matlab/mex/.build/nnfullyconnected.o matlab/mex/.build/nnsubsample.o matlab/mex/.build/nnpooling.o matlab/mex/.build/nnnormalize.o matlab/mex/.build/impl/im2row_cpu.o matlab/mex/.build/impl/subsample_cpu.o matlab/mex/.build/impl/copy_cpu.o matlab/mex/.build/impl/pooling_cpu.o matlab/mex/.build/impl/normalize_cpu.o matlab/mex/.build/impl/tinythread.o matlab/mex/.build/impl/imread_quartz.o matlab/mex/.build/impl/im2row_gpu.o matlab/mex/.build/impl/subsample_gpu.o matlab/mex/.build/impl/copy_gpu.o matlab/mex/.build/impl/pooling_gpu.o matlab/mex/.build/impl/normalize_gpu.o matlab/mex/.build/datacu.o 
Building with 'Xcode Clang++'.
Undefined symbols for architecture x86_64:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(char const*, unsigned long)", referenced from:
      vl::Context::passError(vl::Error, char const*) in data.o
      vl::Context::setError(vl::Error, char const*) in data.o
      vl::MexTensor::init(vl::Device, vl::TensorGeometry const&, float) in datamex.o
      vl::CudaHelper::catchCublasError(cublasStatus_t, char const*) in datacu.o
      vl::CudaHelper::catchCudaError(char const*) in datacu.o
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(char const*, unsigned long, unsigned long)", referenced from:
      vl::Context::passError(vl::Error, char const*) in data.o
      vl::Context::setError(vl::Error, char const*) in data.o
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*) in data.o
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*) in datamex.o
      vl::CudaHelper::catchCublasError(cublasStatus_t, char const*) in datacu.o
      vl::CudaHelper::catchCudaError(char const*) in datacu.o
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*) in datacu.o
      ...
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(char const*, unsigned long)", referenced from:
      vl::Context::passError(vl::Error, char const*) in data.o
      vl::Context::setError(vl::Error, char const*) in data.o
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*) in data.o
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*) in datamex.o
      vl::CudaHelper::catchCublasError(cublasStatus_t, char const*) in datacu.o
      vl::CudaHelper::catchCudaError(char const*) in datacu.o
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*) in datacu.o
      ...
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      vl::Context::setError(vl::Error, char const*) in data.o
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()", referenced from:
      vl::Context::~Context() in data.o
      vl::Context::~Context() in data.o
      vl::Context::resetLastError() in data.o
      vl::Context::passError(vl::Error, char const*) in data.o
      vl::Context::setError(vl::Error, char const*) in data.o
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*) in data.o
      vl::MexTensor::init(vl::Device, vl::TensorGeometry const&, float) in datamex.o
      ...
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::operator=(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      vl::Context::resetLastError() in data.o
      vl::Context::passError(vl::Error, char const*) in data.o
      vl::Context::setError(vl::Error, char const*) in data.o
      vl::CudaHelper::catchCublasError(cublasStatus_t, char const*) in datacu.o
      vl::CudaHelper::catchCudaError(char const*) in datacu.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

make: *** [matlab/mex/vl_nnconv.mexmaci64] Error 255
nbgusmao:matconvnet pedro$ 
```
However, if I don't use libstd++ ( and instead implicitly use libc++ from clang ), I correctly get (except from some warnings):

```
MEX completed successfully.
/Developer/NVIDIA/CUDA-7.0/bin/nvcc -gencode=arch=compute_30,code=\"sm_30,compute_30\" -DENABLE_GPU  -I"/Applications/MATLAB_R2014a.app/extern/include" -I"/Applications/MATLAB_R2014a.app/toolbox/distcomp/gpu/extern/include" -Xcompiler -fPIC -DNDEBUG -O3 -g -Xcompiler -fPIC \
	"matlab/src/vl_nnpool.cu" -c -o "matlab/mex/.build/vl_nnpool.o" 2> >( sed 's/^\(.*\)(\([0-9][0-9]*\)): \([ew].*\)/\1:\2: \3/g' >&2 )
/Applications/MATLAB_R2014a.app/bin/mex -cxx -largeArrayDims -lmwblas -DENABLE_GPU   -DNDEBUG -O CXXOPTIMFLAGS='$CXXOPTIMFLAGS -g' LDOPTIMFLAGS='$LDOPTIMFLAGS -g'  LDFLAGS='$LDFLAGS -framework Cocoa -framework ImageIO' -lmwgpu -L/Developer/NVIDIA/CUDA-7.0/lib LDFLAGS='$LDFLAGS '  -lcublas -lcudart  "matlab/mex/.build/vl_nnpool.o" -output "matlab/mex/vl_nnpool.mexmaci64" matlab/mex/.build/data.o matlab/mex/.build/datamex.o matlab/mex/.build/nnconv.o matlab/mex/.build/nnbias.o matlab/mex/.build/nnfullyconnected.o matlab/mex/.build/nnsubsample.o matlab/mex/.build/nnpooling.o matlab/mex/.build/nnnormalize.o matlab/mex/.build/impl/im2row_cpu.o matlab/mex/.build/impl/subsample_cpu.o matlab/mex/.build/impl/copy_cpu.o matlab/mex/.build/impl/pooling_cpu.o matlab/mex/.build/impl/normalize_cpu.o matlab/mex/.build/impl/tinythread.o matlab/mex/.build/impl/imread_quartz.o matlab/mex/.build/impl/im2row_gpu.o matlab/mex/.build/impl/subsample_gpu.o matlab/mex/.build/impl/copy_gpu.o matlab/mex/.build/impl/pooling_gpu.o matlab/mex/.build/impl/normalize_gpu.o matlab/mex/.build/datacu.o 
Building with 'Xcode Clang++'.
MEX completed successfully.
/Developer/NVIDIA/CUDA-7.0/bin/nvcc -gencode=arch=compute_30,code=\"sm_30,compute_30\" -DENABLE_GPU  -I"/Applications/MATLAB_R2014a.app/extern/include" -I"/Applications/MATLAB_R2014a.app/toolbox/distcomp/gpu/extern/include" -Xcompiler -fPIC -DNDEBUG -O3 -g -Xcompiler -fPIC \
	"matlab/src/vl_nnnormalize.cu" -c -o "matlab/mex/.build/vl_nnnormalize.o" 2> >( sed 's/^\(.*\)(\([0-9][0-9]*\)): \([ew].*\)/\1:\2: \3/g' >&2 )
/Applications/MATLAB_R2014a.app/bin/mex -cxx -largeArrayDims -lmwblas -DENABLE_GPU   -DNDEBUG -O CXXOPTIMFLAGS='$CXXOPTIMFLAGS -g' LDOPTIMFLAGS='$LDOPTIMFLAGS -g'  LDFLAGS='$LDFLAGS -framework Cocoa -framework ImageIO' -lmwgpu -L/Developer/NVIDIA/CUDA-7.0/lib LDFLAGS='$LDFLAGS '  -lcublas -lcudart  "matlab/mex/.build/vl_nnnormalize.o" -output "matlab/mex/vl_nnnormalize.mexmaci64" matlab/mex/.build/data.o matlab/mex/.build/datamex.o matlab/mex/.build/nnconv.o matlab/mex/.build/nnbias.o matlab/mex/.build/nnfullyconnected.o matlab/mex/.build/nnsubsample.o matlab/mex/.build/nnpooling.o matlab/mex/.build/nnnormalize.o matlab/mex/.build/impl/im2row_cpu.o matlab/mex/.build/impl/subsample_cpu.o matlab/mex/.build/impl/copy_cpu.o matlab/mex/.build/impl/pooling_cpu.o matlab/mex/.build/impl/normalize_cpu.o matlab/mex/.build/impl/tinythread.o matlab/mex/.build/impl/imread_quartz.o matlab/mex/.build/impl/im2row_gpu.o matlab/mex/.build/impl/subsample_gpu.o matlab/mex/.build/impl/copy_gpu.o matlab/mex/.build/impl/pooling_gpu.o matlab/mex/.build/impl/normalize_gpu.o matlab/mex/.build/datacu.o 
Building with 'Xcode Clang++'.
MEX completed successfully.
/Developer/NVIDIA/CUDA-7.0/bin/nvcc -gencode=arch=compute_30,code=\"sm_30,compute_30\" -DENABLE_GPU  -I"/Applications/MATLAB_R2014a.app/extern/include" -I"/Applications/MATLAB_R2014a.app/toolbox/distcomp/gpu/extern/include" -Xcompiler -fPIC -DNDEBUG -O3 -g -Xcompiler -fPIC \
	"matlab/src/vl_imreadjpeg.cu" -c -o "matlab/mex/.build/vl_imreadjpeg.o" 2> >( sed 's/^\(.*\)(\([0-9][0-9]*\)): \([ew].*\)/\1:\2: \3/g' >&2 )
matlab/src/bits/impl/tinythread.h:654: warning: extra ";" ignored

matlab/src/vl_imreadjpeg.cu:223: warning: variable "num" was declared but never referenced

matlab/src/bits/impl/tinythread.h:654: warning: extra ";" ignored

matlab/src/vl_imreadjpeg.cu:223: warning: variable "num" was declared but never referenced

/Applications/MATLAB_R2014a.app/bin/mex -cxx -largeArrayDims -lmwblas -DENABLE_GPU   -DNDEBUG -O CXXOPTIMFLAGS='$CXXOPTIMFLAGS -g' LDOPTIMFLAGS='$LDOPTIMFLAGS -g'  LDFLAGS='$LDFLAGS -framework Cocoa -framework ImageIO' -lmwgpu -L/Developer/NVIDIA/CUDA-7.0/lib LDFLAGS='$LDFLAGS '  -lcublas -lcudart  "matlab/mex/.build/vl_imreadjpeg.o" -output "matlab/mex/vl_imreadjpeg.mexmaci64" matlab/mex/.build/data.o matlab/mex/.build/datamex.o matlab/mex/.build/nnconv.o matlab/mex/.build/nnbias.o matlab/mex/.build/nnfullyconnected.o matlab/mex/.build/nnsubsample.o matlab/mex/.build/nnpooling.o matlab/mex/.build/nnnormalize.o matlab/mex/.build/impl/im2row_cpu.o matlab/mex/.build/impl/subsample_cpu.o matlab/mex/.build/impl/copy_cpu.o matlab/mex/.build/impl/pooling_cpu.o matlab/mex/.build/impl/normalize_cpu.o matlab/mex/.build/impl/tinythread.o matlab/mex/.build/impl/imread_quartz.o matlab/mex/.build/impl/im2row_gpu.o matlab/mex/.build/impl/subsample_gpu.o matlab/mex/.build/impl/copy_gpu.o matlab/mex/.build/impl/pooling_gpu.o matlab/mex/.build/impl/normalize_gpu.o matlab/mex/.build/datacu.o 
Building with 'Xcode Clang++'.
MEX completed successfully.
```

My specific configurations are: 
```
nbgusmao:matconvnet pedro$ clang++ --version
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
nbgusmao:matconvnet pedro$ g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
nbgusmao:matconvnet pedro$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Feb_16_23:23:36_CST_2015
Cuda compilation tools, release 7.0, V7.0.27
```

Output of running  `make info` without  `-stdlib=stdlibc++` in the `MEXFLAGS_NVCC` is:
```
nbgusmao:matconvnet pedro$ make ARCH=maci64 MATLABROOT=/Applications/MATLAB_R2014a.app ENABLE_GPU=yes CUDAROOT=/Developer/NVIDIA/CUDA-7.0 CUDAMETHOD=nvcc info
mds=doc/site/docs/about.md doc/site/docs/developers.md doc/site/docs/functions.md doc/site/docs/gpu.md doc/site/docs/index.md doc/site/docs/install-alt.md doc/site/docs/install.md doc/site/docs/pretrained.md doc/site/docs/training.md
mfile_src=matlab/src/vl_argparse.m matlab/src/vl_compilenn.m matlab/src/vl_nnbnorm.m matlab/src/vl_nnconv.m matlab/src/vl_nnconvt.m matlab/src/vl_nndropout.m matlab/src/vl_nnloss.m matlab/src/vl_nnnoffset.m matlab/src/vl_nnnormalize.m matlab/src/vl_nnpdist.m matlab/src/vl_nnpool.m matlab/src/vl_nnrelu.m matlab/src/vl_nnsigmoid.m matlab/src/vl_nnsoftmax.m matlab/src/vl_nnsoftmaxloss.m matlab/src/vl_nnspnorm.m matlab/src/vl_rootnn.m matlab/src/vl_setupnn.m matlab/src/vl_simplenn.m matlab/src/vl_simplenn_diagnose.m matlab/src/vl_simplenn_display.m matlab/src/vl_simplenn_move.m
mfile_doc=doc/site/docs/mfiles/vl_argparse.md doc/site/docs/mfiles/vl_compilenn.md doc/site/docs/mfiles/vl_nnbnorm.md doc/site/docs/mfiles/vl_nnconv.md doc/site/docs/mfiles/vl_nnconvt.md doc/site/docs/mfiles/vl_nndropout.md doc/site/docs/mfiles/vl_nnloss.md doc/site/docs/mfiles/vl_nnnoffset.md doc/site/docs/mfiles/vl_nnnormalize.md doc/site/docs/mfiles/vl_nnpdist.md doc/site/docs/mfiles/vl_nnpool.md doc/site/docs/mfiles/vl_nnrelu.md doc/site/docs/mfiles/vl_nnsigmoid.md doc/site/docs/mfiles/vl_nnsoftmax.md doc/site/docs/mfiles/vl_nnsoftmaxloss.md doc/site/docs/mfiles/vl_nnspnorm.md doc/site/docs/mfiles/vl_rootnn.md doc/site/docs/mfiles/vl_setupnn.md doc/site/docs/mfiles/vl_simplenn.md doc/site/docs/mfiles/vl_simplenn_diagnose.md doc/site/docs/mfiles/vl_simplenn_display.md doc/site/docs/mfiles/vl_simplenn_move.md
mex_src= matlab/src/vl_nnconv.cu matlab/src/vl_nnconvt.cu matlab/src/vl_nnpool.cu matlab/src/vl_nnnormalize.cu matlab/src/vl_imreadjpeg.cpp
mex_tgt=matlab/mex/vl_nnconv.mexmaci64 matlab/mex/vl_nnconvt.mexmaci64 matlab/mex/vl_nnpool.mexmaci64 matlab/mex/vl_nnnormalize.mexmaci64 matlab/mex/vl_imreadjpeg.mexmaci64
cpp_src= matlab/src/bits/data.cu matlab/src/bits/datamex.cu matlab/src/bits/nnconv.cu matlab/src/bits/nnbias.cu matlab/src/bits/nnfullyconnected.cu matlab/src/bits/nnsubsample.cu matlab/src/bits/nnpooling.cu matlab/src/bits/nnnormalize.cu matlab/src/bits/impl/im2row_cpu.cpp matlab/src/bits/impl/subsample_cpu.cpp matlab/src/bits/impl/copy_cpu.cpp matlab/src/bits/impl/pooling_cpu.cpp matlab/src/bits/impl/normalize_cpu.cpp matlab/src/bits/impl/tinythread.cpp matlab/src/bits/impl/imread_quartz.cpp matlab/src/bits/impl/im2row_gpu.cu matlab/src/bits/impl/subsample_gpu.cu matlab/src/bits/impl/copy_gpu.cu matlab/src/bits/impl/pooling_gpu.cu matlab/src/bits/impl/normalize_gpu.cu matlab/src/bits/datacu.cu
cpp_tgt=matlab/mex/.build/data.o matlab/mex/.build/datamex.o matlab/mex/.build/nnconv.o matlab/mex/.build/nnbias.o matlab/mex/.build/nnfullyconnected.o matlab/mex/.build/nnsubsample.o matlab/mex/.build/nnpooling.o matlab/mex/.build/nnnormalize.o matlab/mex/.build/impl/im2row_cpu.o matlab/mex/.build/impl/subsample_cpu.o matlab/mex/.build/impl/copy_cpu.o matlab/mex/.build/impl/pooling_cpu.o matlab/mex/.build/impl/normalize_cpu.o matlab/mex/.build/impl/tinythread.o matlab/mex/.build/impl/imread_quartz.o matlab/mex/.build/impl/im2row_gpu.o matlab/mex/.build/impl/subsample_gpu.o matlab/mex/.build/impl/copy_gpu.o matlab/mex/.build/impl/pooling_gpu.o matlab/mex/.build/impl/normalize_gpu.o matlab/mex/.build/datacu.o
cu_src=
cu_tgt=
MEXFLAGS=-cxx -largeArrayDims -lmwblas -DENABLE_GPU   -DNDEBUG -O CXXOPTIMFLAGS= -g LDOPTIMFLAGS= -g  LDFLAGS= -framework Cocoa -framework ImageIO
MEXFLAGS_GPU=-cxx -largeArrayDims -lmwblas -DENABLE_GPU   -DNDEBUG -O CXXOPTIMFLAGS= -g LDOPTIMFLAGS= -g  LDFLAGS= -framework Cocoa -framework ImageIO -f "matlab/src/config/mex_CUDA_maci64.xml" -L/Developer/NVIDIA/CUDA-7.0/lib -lcublas -lcudart 
MEXFLAGS_NVCC=-cxx -largeArrayDims -lmwblas -DENABLE_GPU   -DNDEBUG -O CXXOPTIMFLAGS= -g LDOPTIMFLAGS= -g  LDFLAGS= -framework Cocoa -framework ImageIO -lmwgpu -L/Developer/NVIDIA/CUDA-7.0/lib LDFLAGS=   -lcublas -lcudart 
NVCCFLAGS=-gencode=arch=compute_30,code=\"sm_30,compute_30\" -DENABLE_GPU  -I"/Applications/MATLAB_R2014a.app/extern/include" -I"/Applications/MATLAB_R2014a.app/toolbox/distcomp/gpu/extern/include" -Xcompiler -fPIC -DNDEBUG -O3 -g
```

Output of running  `make info` with  `-stdlib=stdlibc++` in the `MEXFLAGS_NVCC` is:
```
nbgusmao:matconvnet pedro$ make ARCH=maci64 MATLABROOT=/Applications/MATLAB_R2014a.app ENABLE_GPU=yes CUDAROOT=/Developer/NVIDIA/CUDA-7.0 CUDAMETHOD=nvcc info
mds=doc/site/docs/about.md doc/site/docs/developers.md doc/site/docs/functions.md doc/site/docs/gpu.md doc/site/docs/index.md doc/site/docs/install-alt.md doc/site/docs/install.md doc/site/docs/pretrained.md doc/site/docs/training.md
mfile_src=matlab/src/vl_argparse.m matlab/src/vl_compilenn.m matlab/src/vl_nnbnorm.m matlab/src/vl_nnconv.m matlab/src/vl_nnconvt.m matlab/src/vl_nndropout.m matlab/src/vl_nnloss.m matlab/src/vl_nnnoffset.m matlab/src/vl_nnnormalize.m matlab/src/vl_nnpdist.m matlab/src/vl_nnpool.m matlab/src/vl_nnrelu.m matlab/src/vl_nnsigmoid.m matlab/src/vl_nnsoftmax.m matlab/src/vl_nnsoftmaxloss.m matlab/src/vl_nnspnorm.m matlab/src/vl_rootnn.m matlab/src/vl_setupnn.m matlab/src/vl_simplenn.m matlab/src/vl_simplenn_diagnose.m matlab/src/vl_simplenn_display.m matlab/src/vl_simplenn_move.m
mfile_doc=doc/site/docs/mfiles/vl_argparse.md doc/site/docs/mfiles/vl_compilenn.md doc/site/docs/mfiles/vl_nnbnorm.md doc/site/docs/mfiles/vl_nnconv.md doc/site/docs/mfiles/vl_nnconvt.md doc/site/docs/mfiles/vl_nndropout.md doc/site/docs/mfiles/vl_nnloss.md doc/site/docs/mfiles/vl_nnnoffset.md doc/site/docs/mfiles/vl_nnnormalize.md doc/site/docs/mfiles/vl_nnpdist.md doc/site/docs/mfiles/vl_nnpool.md doc/site/docs/mfiles/vl_nnrelu.md doc/site/docs/mfiles/vl_nnsigmoid.md doc/site/docs/mfiles/vl_nnsoftmax.md doc/site/docs/mfiles/vl_nnsoftmaxloss.md doc/site/docs/mfiles/vl_nnspnorm.md doc/site/docs/mfiles/vl_rootnn.md doc/site/docs/mfiles/vl_setupnn.md doc/site/docs/mfiles/vl_simplenn.md doc/site/docs/mfiles/vl_simplenn_diagnose.md doc/site/docs/mfiles/vl_simplenn_display.md doc/site/docs/mfiles/vl_simplenn_move.md
mex_src= matlab/src/vl_nnconv.cu matlab/src/vl_nnconvt.cu matlab/src/vl_nnpool.cu matlab/src/vl_nnnormalize.cu matlab/src/vl_imreadjpeg.cpp
mex_tgt=matlab/mex/vl_nnconv.mexmaci64 matlab/mex/vl_nnconvt.mexmaci64 matlab/mex/vl_nnpool.mexmaci64 matlab/mex/vl_nnnormalize.mexmaci64 matlab/mex/vl_imreadjpeg.mexmaci64
cpp_src= matlab/src/bits/data.cu matlab/src/bits/datamex.cu matlab/src/bits/nnconv.cu matlab/src/bits/nnbias.cu matlab/src/bits/nnfullyconnected.cu matlab/src/bits/nnsubsample.cu matlab/src/bits/nnpooling.cu matlab/src/bits/nnnormalize.cu matlab/src/bits/impl/im2row_cpu.cpp matlab/src/bits/impl/subsample_cpu.cpp matlab/src/bits/impl/copy_cpu.cpp matlab/src/bits/impl/pooling_cpu.cpp matlab/src/bits/impl/normalize_cpu.cpp matlab/src/bits/impl/tinythread.cpp matlab/src/bits/impl/imread_quartz.cpp matlab/src/bits/impl/im2row_gpu.cu matlab/src/bits/impl/subsample_gpu.cu matlab/src/bits/impl/copy_gpu.cu matlab/src/bits/impl/pooling_gpu.cu matlab/src/bits/impl/normalize_gpu.cu matlab/src/bits/datacu.cu
cpp_tgt=matlab/mex/.build/data.o matlab/mex/.build/datamex.o matlab/mex/.build/nnconv.o matlab/mex/.build/nnbias.o matlab/mex/.build/nnfullyconnected.o matlab/mex/.build/nnsubsample.o matlab/mex/.build/nnpooling.o matlab/mex/.build/nnnormalize.o matlab/mex/.build/impl/im2row_cpu.o matlab/mex/.build/impl/subsample_cpu.o matlab/mex/.build/impl/copy_cpu.o matlab/mex/.build/impl/pooling_cpu.o matlab/mex/.build/impl/normalize_cpu.o matlab/mex/.build/impl/tinythread.o matlab/mex/.build/impl/imread_quartz.o matlab/mex/.build/impl/im2row_gpu.o matlab/mex/.build/impl/subsample_gpu.o matlab/mex/.build/impl/copy_gpu.o matlab/mex/.build/impl/pooling_gpu.o matlab/mex/.build/impl/normalize_gpu.o matlab/mex/.build/datacu.o
cu_src=
cu_tgt=
MEXFLAGS=-cxx -largeArrayDims -lmwblas -DENABLE_GPU   -DNDEBUG -O CXXOPTIMFLAGS= -g LDOPTIMFLAGS= -g  LDFLAGS= -framework Cocoa -framework ImageIO
MEXFLAGS_GPU=-cxx -largeArrayDims -lmwblas -DENABLE_GPU   -DNDEBUG -O CXXOPTIMFLAGS= -g LDOPTIMFLAGS= -g  LDFLAGS= -framework Cocoa -framework ImageIO -f "matlab/src/config/mex_CUDA_maci64.xml" -L/Developer/NVIDIA/CUDA-7.0/lib -lcublas -lcudart 
MEXFLAGS_NVCC=-cxx -largeArrayDims -lmwblas -DENABLE_GPU   -DNDEBUG -O CXXOPTIMFLAGS= -g LDOPTIMFLAGS= -g  LDFLAGS= -framework Cocoa -framework ImageIO -lmwgpu -L/Developer/NVIDIA/CUDA-7.0/lib LDFLAGS= -stdlib=libstdc++ -lcublas -lcudart 
NVCCFLAGS=-gencode=arch=compute_30,code=\"sm_30,compute_30\" -DENABLE_GPU  -I"/Applications/MATLAB_R2014a.app/extern/include" -I"/Applications/MATLAB_R2014a.app/toolbox/distcomp/gpu/extern/include" -Xcompiler -fPIC -DNDEBUG -O3 -g
``` 

I hope this report can help.
Could using libc++ instead of libstdc++ generate a problem?

**Comment by lenck** [comment]
Hi, this seems to be [fixed](https://github.com/vlfeat/matconvnet/blob/master/matlab/vl_compilenn.m#L402). Can you check if it works?

**Comment by pedropgusmao** [comment]
It probably is. It's been some time I have tried it. I will try it again tonight and let you know... Thanks

**Comment by lenck** [comment]
Great! :) Sorry that it took so long to respond to you...

**Comment by pedropgusmao** [comment]
No problem. 
I have just compiled it using OS X10.11.4 El Capitan with X Code 7.3 and Matlab 2015b and it worked :+1: 
First I had to fix the Xcode-matlab2015b compatibility issue reported in  [here](http://it.mathworks.com/matlabcentral/answers/246507-why-can-t-mex-find-a-supported-compiler-in-matlab-r2015b-after-i-upgraded-to-xcode-7-0#answer_194526) but then it worked.
By the way, is there a way could of help to this project? I have been wanting to participate in an open source project involving convnets.

Thanks
