### ISSUE TITLE
nnconv_forward_blas cuda error (vl_nnconv)

### ISSUE THREAD

**Issue by tinalegre** [vlfeat/matconvnet#312]
Is the following error message known to any of you?
![cuda_error](http://i.imgur.com/NMAcqrB.png)

I'm using **matlab 2015b+cuda v. 7.5**. I was previouly using **matlab 2014a+cuda v6.5** and no errors appeared. After first compiling **matconvnet** with CPU only, I compiled **matconvnet** with GPU support:
```
vl_compilenn('enableGpu', true, 'cudaRoot', '/usr/local/cuda-7.5/','cudaMethod', 'nvcc', 'verbose', 1);
```
Any ideas? I've re-installed/re-compiled **matconvnet** a couple of times with no success. When I deactive the GPU support (**opts.train.gpus=[]**), the training is done correctly.

**Comment by grantlj** [comment]
I meet this problem  as well. my version is beta16

**Comment by tinalegre** [comment]
@grantlj I still haven't solved that issue. What combination of matlab and cuda version are you using? Are you also using linux? Please let me know, if you find a solution ;-)

**Comment by grantlj** [comment]
Yes, I solved it. Our Matlab version is R2014b running on the Ubuntu 12.04LTS. And our machine is accelerated by a GTX TITAN X card along with CUDA7.0.

The solution is merely decreasing the size of the batch and sub-batch :)  (out of memory?)
I think the main reason is that vl_nnconv function doesn't provide essential debug info on this issue. Maybe they will fix it in next version.

**Comment by tinalegre** [comment]
@grantlj, thanks! I initially thought it was something related to the compatibility between matlab+cuda. But now that you're using Matlab 2014b+Cuda 7.0 without any problems means that one does not need to have the exact configuration as suggested [here!](http://www.vlfeat.org/matconvnet/install/).

**Comment by brealisty** [comment]
@grantlj  I meet the same problem(out of memory), how to decrease the size of the batch?

**Comment by grantlj** [comment]
@brealisty For instance, if you are training a linear (rather than DAG network) network, you may refer to: https://github.com/vlfeat/matconvnet/blob/master/examples/cnn_train.m. In line 23: opts.batchSize = 256. You could change 256 to a smaller value, so that it could consume less GPU memories.
